### ISSUE TITLE
Licensing (Again)

### ISSUE THREAD

**Issue by aharui** [designmodo/Flat-UI#213]
Hi, we noticed in issue #18 that you are offering Flat Free under MIT, but someone noticed that the font files actually have a CC noncommercial license and is therefore claiming those files aren't under MIT.  Can you clarify the licensing of the glyph icons?

Thanks,
-Alex

**Comment by justinmclean** [comment]
Hi,

Perhaps a little further detail will help.

The files in question are: flat-ui-icons-regular.eot, flat-ui-icons-regular.ttf, flat-ui-icons-regular.woff, lat-ui-icons-regular.svg and they seem to be licensed under a Attribution Non Commercial No Derivatives CC license. From the svg file:
	"fontURL": "http://designmodo.com/flat",
        "designer": "Sergey Shmidt",
        "designerURL": "http://designmodo.com",
        "license": "Attribution-NonCommercial-NoDerivs 3.0 Unported",
        "licenseURL": "http://creativecommons.org/licenses/by-nc-nd/3.0/“,

The TTF file has the same license in it meta data.

We would like to include these font files in an Apache Flex release which is under an Apache 2.0 license and distribute them as part of that release. In order to be able to do this we would need those individual font files to be relicensed under Apache, MIT or BSD licenses.

Thanks,
Justin

**Comment by aharui** [comment]
It may also be ok to use a Creative Commons license that doesn't have NonCommercial or NonDerivs.

**Comment by glerinsonum** [comment]
@justinmclean Hello Brother. I need for your help. 

My question is this
**How can I make an HTML Builder with effect Drag & Drop UI Interactions for to build responsive websites in minutes, like this [**](@justinmclean Hello Brother. I need for your help. 

My question is this
**How can I make an HTML Builder with effect Drag & Drop UI Interactions for to build responsive websites in minutes, like this http://www.bootstrapstarterkit.com/bskit-demo/**)
