### ISSUE TITLE
Can you please update flat UI PRO(paid version), adding the last fixes ?

### ISSUE THREAD

**Issue by nicolasmendoza** [designmodo/Flat-UI#229]
Hi, how can I updata my flat UI pro, applying the fixes included on this repo ? . The last commit of Flat UI PRO (paid version) is the December 24 2014.

Thanks.

**Comment by kamilsk** [comment]
Is there any news? And it is strange that the paid version doesn't update. I'm disappointed.

**Comment by kmander** [comment]
Disappointed also :(

**Comment by englishextra** [comment]
@kamilsk @kmander designmodo/Flat-UI is garbage and it has always been. Using bots and spam on blogs and forums the author promoted their (actually his) product that was a hackwork from the start.

Wake up

**Comment by maracuja-juice** [comment]
@englishextra I love the kit but I'm kinda disappointed that it isn't really active even if you payed for it... What are our alternatives?

**Comment by englishextra** [comment]
@maracuja-juice I can't because they are all ugly. So I wrote my own framework and these pages are my guidelines (Microsoft or wharever it doesnt matter):

* [UI](https://www.goodui.org/)
* [Colors](https://www.microsoft.com/en-us/design/color)
* [Icons & Tiles](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/app-assets)
* [Font sizes](http://www.modularscale.com/)

The only repo that I might use for quick prototyping is [mui](https://www.muicss.com/)

**Comment by kmander** [comment]
I like the TransferWise Bootstrap fork (http://bootstrap.transferwise.com/)

**Comment by maracuja-juice** [comment]
@kmander What I like the most about Flat-UI are the included sliders.

**Comment by piromvorn** [comment]
HTC u11

**Comment by maracuja-juice** [comment]
Did you update it? @Designmodocom
It would be nice to also have an explanation for why an issue was closed...
